#!/usr/bin/env bash
# ============================================================================
# tools/patch-ox-items.sh <path-to-deployed-resources-dir>
#
# ox_inventory builds its ItemList ONLY from its own data/items.lua
# (modules/items/shared.lua -> lib.load('data.items')); the Items() export
# returns a msgpack COPY, so ox_inventory_overrides' runtime merge can never
# reach it. This script is the declarative half: it copies the ExtraItems
# definitions from resources/[custom]/[config_overrides]/ox_inventory_overrides/
# data/items.lua into the deployed ox_inventory/data/items.lua between
# GTARP markers. Idempotent — re-running replaces the marker block.
#
#   bash tools/patch-ox-items.sh "/c/.../txData/Qbox_455D8A.base/resources"
#
# Run this after every recipe update or fresh deploy, BEFORE boot. The
# overrides resource verifies registration at boot and prints a FATAL line
# naming any item that didn't land.
# ============================================================================
set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$REPO/resources/[custom]/[config_overrides]/ox_inventory_overrides/data/items.lua"
RES_DIR="${1:?usage: patch-ox-items.sh <deployed-resources-dir>}"
TARGET="$RES_DIR/[ox]/ox_inventory/data/items.lua"

[ -f "$SRC" ]    || { echo "ERROR: missing $SRC" >&2; exit 1; }
[ -f "$TARGET" ] || { echo "ERROR: missing $TARGET (wrong resources dir?)" >&2; exit 1; }

# native python on Windows can't open /c/... paths — hand it native ones
if command -v cygpath >/dev/null 2>&1; then
  SRC="$(cygpath -w "$SRC")"; TARGET="$(cygpath -w "$TARGET")"
fi

python - "$SRC" "$TARGET" <<'PY'
import re, sys

src, target = sys.argv[1], sys.argv[2]
BEGIN = "    -- >>> GTARP EXTRA ITEMS (generated by tools/patch-ox-items.sh — do not edit here)"
END   = "    -- <<< GTARP EXTRA ITEMS"

text = open(src, encoding="utf-8").read()
m = re.search(r"ExtraItems\s*=\s*\{(.*)\n\}", text, re.S)
if not m:
    sys.exit("ERROR: could not find ExtraItems table in overrides items.lua")
body = m.group(1)

# name = { ... }  ->  ['name'] = { ... }  (ox_inventory file style)
body = re.sub(r"(?m)^(\s*)([A-Za-z_][A-Za-z0-9_]*)(\s*=\s*\{)", r"\1['\2']\3", body)

out = open(target, encoding="utf-8").read()

# never shadow an item ox_inventory already defines (later table keys win in
# Lua, so a duplicate here would silently override the recipe's definition)
existing = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n", "", out, flags=re.S) if BEGIN in out else out
lines, keep, skipped = body.split("\n"), [], []
drop = False
for ln in lines:
    m2 = re.match(r"\s*\['([A-Za-z0-9_]+)'\]\s*=\s*\{", ln)
    if m2:
        drop = re.search(r"\['" + m2.group(1) + r"'\]\s*=", existing) is not None
        if drop: skipped.append(m2.group(1))
    if not drop:
        keep.append(ln)
body = "\n".join(keep)
if skipped:
    print("skipped (already defined by ox_inventory): " + ", ".join(sorted(set(skipped))))
block = f"{BEGIN}{body}\n{END}\n"
if BEGIN in out:
    out = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n", block, out, flags=re.S)
    action = "replaced"
else:
    close = out.rstrip().rfind("\n}")
    if close < 0:
        sys.exit("ERROR: could not find closing brace of ox_inventory data/items.lua")
    out = out[:close] + "\n\n" + block + out[close:]
    action = "inserted"

open(target, "w", encoding="utf-8", newline="\n").write(out)
names = re.findall(r"\['([A-Za-z0-9_]+)'\]\s*=\s*\{", block)
print(f"{action} {len(names)} item(s) into {target}:")
print("  " + ", ".join(sorted(names)))
PY
