-- Palm6 rebrand: one-time prod table rename. RUN DURING MAINTENANCE WINDOW
-- (server STOPPED) so no resource CREATE TABLE IF NOT EXISTS races the rename.
-- Each guarded: renames only if the gtarp_ table still exists (idempotent).
-- Generated from live CREATE TABLE list (64 tables).

SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_bounty_contracts');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_bounty_contracts');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_bounty_contracts` TO `palm6_bounty_contracts`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_chopshop_sales');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_chopshop_sales');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_chopshop_sales` TO `palm6_chopshop_sales`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_chopshop_stolen');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_chopshop_stolen');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_chopshop_stolen` TO `palm6_chopshop_stolen`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_citations');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_citations');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_citations` TO `palm6_citations`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_clout_deals');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_clout_deals');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_clout_deals` TO `palm6_clout_deals`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_clout_streamers');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_clout_streamers');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_clout_streamers` TO `palm6_clout_streamers`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_clout_vod');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_clout_vod');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_clout_vod` TO `palm6_clout_vod`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_counterfeit_batches');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_counterfeit_batches');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_counterfeit_batches` TO `palm6_counterfeit_batches`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_counterfeit_heat');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_counterfeit_heat');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_counterfeit_heat` TO `palm6_counterfeit_heat`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_counterfeit_hops');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_counterfeit_hops');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_counterfeit_hops` TO `palm6_counterfeit_hops`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_counterfeit_leads');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_counterfeit_leads');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_counterfeit_leads` TO `palm6_counterfeit_leads`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_counterfeit_printers');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_counterfeit_printers');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_counterfeit_printers` TO `palm6_counterfeit_printers`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_counterfeit_wads');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_counterfeit_wads');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_counterfeit_wads` TO `palm6_counterfeit_wads`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_drugs_dealers');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_drugs_dealers');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_drugs_dealers` TO `palm6_drugs_dealers`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_drugs_plants');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_drugs_plants');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_drugs_plants` TO `palm6_drugs_plants`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_drugs_processes');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_drugs_processes');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_drugs_processes` TO `palm6_drugs_processes`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_drugs_progression');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_drugs_progression');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_drugs_progression` TO `palm6_drugs_progression`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_drugs_recipes');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_drugs_recipes');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_drugs_recipes` TO `palm6_drugs_recipes`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_drugs_sales');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_drugs_sales');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_drugs_sales` TO `palm6_drugs_sales`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_evidence');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_evidence');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_evidence` TO `palm6_evidence`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_evidence_cases');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_evidence_cases');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_evidence_cases` TO `palm6_evidence_cases`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_evidence_suspects');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_evidence_suspects');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_evidence_suspects` TO `palm6_evidence_suspects`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_fightclub_bets');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_fightclub_bets');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_fightclub_bets` TO `palm6_fightclub_bets`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_fightclub_matches');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_fightclub_matches');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_fightclub_matches` TO `palm6_fightclub_matches`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_flashdrop_drops');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_flashdrop_drops');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_flashdrop_drops` TO `palm6_flashdrop_drops`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_flashdrop_listings');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_flashdrop_listings');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_flashdrop_listings` TO `palm6_flashdrop_listings`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_flashdrop_provenance');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_flashdrop_provenance');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_flashdrop_provenance` TO `palm6_flashdrop_provenance`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_flashdrop_serials');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_flashdrop_serials');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_flashdrop_serials` TO `palm6_flashdrop_serials`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_gang_members');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_gang_members');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_gang_members` TO `palm6_gang_members`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_gang_vault_log');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_gang_vault_log');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_gang_vault_log` TO `palm6_gang_vault_log`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_gang_web_tokens');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_gang_web_tokens');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_gang_web_tokens` TO `palm6_gang_web_tokens`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_gangs');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_gangs');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_gangs` TO `palm6_gangs`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_gunrunning_sales');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_gunrunning_sales');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_gunrunning_sales` TO `palm6_gunrunning_sales`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_insurance_claims');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_insurance_claims');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_insurance_claims` TO `palm6_insurance_claims`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_insurance_policies');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_insurance_policies');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_insurance_policies` TO `palm6_insurance_policies`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_laundering_runs');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_laundering_runs');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_laundering_runs` TO `palm6_laundering_runs`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_legal_petitions');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_legal_petitions');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_legal_petitions` TO `palm6_legal_petitions`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_loanshark_loans');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_loanshark_loans');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_loanshark_loans` TO `palm6_loanshark_loans`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_market_state');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_market_state');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_market_state` TO `palm6_market_state`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_market_trades');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_market_trades');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_market_trades` TO `palm6_market_trades`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_mdt_bolos');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_mdt_bolos');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_mdt_bolos` TO `palm6_mdt_bolos`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_mdt_bookings');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_mdt_bookings');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_mdt_bookings` TO `palm6_mdt_bookings`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_mdt_calls');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_mdt_calls');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_mdt_calls` TO `palm6_mdt_calls`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_mdt_reports');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_mdt_reports');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_mdt_reports` TO `palm6_mdt_reports`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_mdt_warrants');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_mdt_warrants');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_mdt_warrants` TO `palm6_mdt_warrants`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_numbers_bets');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_numbers_bets');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_numbers_bets` TO `palm6_numbers_bets`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_numbers_draws');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_numbers_draws');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_numbers_draws` TO `palm6_numbers_draws`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_onboarding');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_onboarding');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_onboarding` TO `palm6_onboarding`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_protection_collections');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_protection_collections');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_protection_collections` TO `palm6_protection_collections`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_pumpcoin_coins');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_pumpcoin_coins');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_pumpcoin_coins` TO `palm6_pumpcoin_coins`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_pumpcoin_holdings');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_pumpcoin_holdings');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_pumpcoin_holdings` TO `palm6_pumpcoin_holdings`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_pumpcoin_trades');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_pumpcoin_trades');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_pumpcoin_trades` TO `palm6_pumpcoin_trades`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_ransom_cases');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_ransom_cases');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_ransom_cases` TO `palm6_ransom_cases`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_replay_participants');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_replay_participants');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_replay_participants` TO `palm6_replay_participants`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_replay_scenes');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_replay_scenes');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_replay_scenes` TO `palm6_replay_scenes`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_seizure_forfeitures');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_seizure_forfeitures');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_seizure_forfeitures` TO `palm6_seizure_forfeitures`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_smuggling_runs');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_smuggling_runs');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_smuggling_runs` TO `palm6_smuggling_runs`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_turf');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_turf');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_turf` TO `palm6_turf`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_witnesses');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_witnesses');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_witnesses` TO `palm6_witnesses`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_witnesses_incidents');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_witnesses_incidents');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_witnesses_incidents` TO `palm6_witnesses_incidents`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_yard_bail');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_yard_bail');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_yard_bail` TO `palm6_yard_bail`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_yard_commissary_log');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_yard_commissary_log');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_yard_commissary_log` TO `palm6_yard_commissary_log`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_yard_labor');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_yard_labor');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_yard_labor` TO `palm6_yard_labor`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @c := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='gtarp_yard_sentence');
SET @d := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='palm6_yard_sentence');
SET @s := IF(@c=1 AND @d=0, 'RENAME TABLE `gtarp_yard_sentence` TO `palm6_yard_sentence`', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
